version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: ship-sale-backend
        restart: unless-stopped
        ports:
            - "${APP_EXTERNAL_PORT:-80}:80"
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE:-laravel}
            - DB_USERNAME=root
            - DB_PASSWORD=${DB_PASSWORD:-password}
        depends_on:
            - db
        networks:
            - laravel-network

    db:
        image: mariadb:10
        restart: unless-stopped
        ports:
            - "${DB_EXTERNAL_PORT:-3306}:3306"
        environment:
            - MARIADB_ROOT_PASSWORD=${DB_PASSWORD:-password}
            - MARIADB_DATABASE=${DB_DATABASE:-laravel}
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "${DB_DATABASE:-laravel}",
                    "-u",
                    "root",
                    "-p${DB_PASSWORD:-password}",
                ]
            interval: 5s
            timeout: 10s
            retries: 10
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel-network

volumes:
    db_data:

networks:
    laravel-network:
        driver: bridge
